# Generated by Django 3.2.18 on 2023-04-11 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitepanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('photo', models.ImageField(blank=True, default='user.png', null=True, upload_to='users_photo/', verbose_name='photo')),
                ('otp', models.IntegerField(default=None, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('verified', models.BooleanField(default=0)),
                ('fcm_token', models.TextField(null=True)),
                ('user_type', models.CharField(choices=[('other', 'Other')], default='unassigned', max_length=30)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('twitter', 'Twitter')], max_length=30)),
                ('social_id', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_username', models.CharField(max_length=255, null=True)),
                ('instagram_username', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_social', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_social',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
