# Generated by Django 3.2.18 on 2023-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepanel', '0003_auto_20230411_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
