# Generated by Django 3.2.23 on 2024-01-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepanel', '0005_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
